# Runtime settings for live execution
concurrency:
  workers: 1

queue:
  capacity: 1000            # event bus capacity; 0 for unbounded
  drop_policy: newest       # "newest" drops incoming, "oldest" drops oldest

ws:
  enabled: true
  persist_path: state/last_bar_seen.json
  log_skips: true

throttle:
  enabled: false              # disable throttling
  global:
    rps: 0.0                  # requests per second; 0 disables
    burst: 0                  # burst capacity
  symbol:
    rps: 0.0                  # per-symbol RPS limit
    burst: 0
  mode: drop                  # drop or queue
  queue:
    max_items: 0              # queue size when mode=queue
    ttl_ms: 0                 # item lifetime in ms
  time_source: "monotonic"

ops:
  kill_switch:
    feed_lag_ms: 60000       # Enter safe mode if worst feed lag exceeds this; 0 disables
    ws_failures: 100         # Enter safe mode if WS failures exceed this count; 0 disables
    error_rate: 0.2          # Enter safe mode if signal error rate exceeds this fraction; 0 disables
    enabled: false           # Enable or disable the ops kill switch
    error_limit: 0           # Maximum allowed consecutive errors; 0 disables
    duplicate_limit: 0       # Maximum allowed duplicate signals; 0 disables
    stale_intervals_limit: 0 # Maximum allowed stale intervals; 0 disables
    reset_cooldown_sec: 60   # Cooldown period before counters reset in seconds
    flag_path: null          # File path acting as external kill flag
    alert_command: null      # Command to execute when kill switch triggers
    # Manual reset: delete the flag file or call ops_kill_switch.manual_reset()
