enabled: false            # Enable or disable signal generation
out_csv: "signals.csv"    # Path to write signals CSV (null to disable)
ttl_seconds: 60           # Time-to-live for signal cache entries
dedup_persist: null       # Path to dedup persistence file or null for in-memory only
fsync_mode: "batch"       # Fsync mode for CSV writer: always/batch/off
rotate_daily: true        # Rotate CSV into <name>-YYYY-MM-DD.csv on day change
flush_interval_s: 5       # Flush interval in seconds for batch/off fsync modes
